// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protocol/picture_management_proto/picture.proto

package picture

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Picture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PictureName string `protobuf:"bytes,1,opt,name=picture_name,json=pictureName,proto3" json:"picture_name,omitempty"`
}

func (x *Picture) Reset() {
	*x = Picture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_picture_management_proto_picture_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Picture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Picture) ProtoMessage() {}

func (x *Picture) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_picture_management_proto_picture_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Picture.ProtoReflect.Descriptor instead.
func (*Picture) Descriptor() ([]byte, []int) {
	return file_protocol_picture_management_proto_picture_proto_rawDescGZIP(), []int{0}
}

func (x *Picture) GetPictureName() string {
	if x != nil {
		return x.PictureName
	}
	return ""
}

type PicturesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PicturesRequest) Reset() {
	*x = PicturesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_picture_management_proto_picture_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicturesRequest) ProtoMessage() {}

func (x *PicturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_picture_management_proto_picture_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicturesRequest.ProtoReflect.Descriptor instead.
func (*PicturesRequest) Descriptor() ([]byte, []int) {
	return file_protocol_picture_management_proto_picture_proto_rawDescGZIP(), []int{1}
}

type PicturesResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Picture []*Picture `protobuf:"bytes,1,rep,name=picture,proto3" json:"picture,omitempty"`
}

func (x *PicturesResponce) Reset() {
	*x = PicturesResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_picture_management_proto_picture_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicturesResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicturesResponce) ProtoMessage() {}

func (x *PicturesResponce) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_picture_management_proto_picture_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicturesResponce.ProtoReflect.Descriptor instead.
func (*PicturesResponce) Descriptor() ([]byte, []int) {
	return file_protocol_picture_management_proto_picture_proto_rawDescGZIP(), []int{2}
}

func (x *PicturesResponce) GetPicture() []*Picture {
	if x != nil {
		return x.Picture
	}
	return nil
}

var File_protocol_picture_management_proto_picture_proto protoreflect.FileDescriptor

var file_protocol_picture_management_proto_picture_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2c, 0x0a, 0x07, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x11, 0x0a, 0x0f, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x36, 0x0a, 0x10, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x32, 0x47, 0x0a, 0x10, 0x50, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x74, 0x12, 0x33,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x10,
	0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_picture_management_proto_picture_proto_rawDescOnce sync.Once
	file_protocol_picture_management_proto_picture_proto_rawDescData = file_protocol_picture_management_proto_picture_proto_rawDesc
)

func file_protocol_picture_management_proto_picture_proto_rawDescGZIP() []byte {
	file_protocol_picture_management_proto_picture_proto_rawDescOnce.Do(func() {
		file_protocol_picture_management_proto_picture_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_picture_management_proto_picture_proto_rawDescData)
	})
	return file_protocol_picture_management_proto_picture_proto_rawDescData
}

var file_protocol_picture_management_proto_picture_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_picture_management_proto_picture_proto_goTypes = []interface{}{
	(*Picture)(nil),          // 0: Picture
	(*PicturesRequest)(nil),  // 1: PicturesRequest
	(*PicturesResponce)(nil), // 2: PicturesResponce
}
var file_protocol_picture_management_proto_picture_proto_depIdxs = []int32{
	0, // 0: PicturesResponce.picture:type_name -> Picture
	1, // 1: PictureManagemet.ListPictures:input_type -> PicturesRequest
	2, // 2: PictureManagemet.ListPictures:output_type -> PicturesResponce
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protocol_picture_management_proto_picture_proto_init() }
func file_protocol_picture_management_proto_picture_proto_init() {
	if File_protocol_picture_management_proto_picture_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_picture_management_proto_picture_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Picture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_picture_management_proto_picture_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicturesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_picture_management_proto_picture_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicturesResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_picture_management_proto_picture_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_picture_management_proto_picture_proto_goTypes,
		DependencyIndexes: file_protocol_picture_management_proto_picture_proto_depIdxs,
		MessageInfos:      file_protocol_picture_management_proto_picture_proto_msgTypes,
	}.Build()
	File_protocol_picture_management_proto_picture_proto = out.File
	file_protocol_picture_management_proto_picture_proto_rawDesc = nil
	file_protocol_picture_management_proto_picture_proto_goTypes = nil
	file_protocol_picture_management_proto_picture_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PictureManagemetClient is the client API for PictureManagemet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PictureManagemetClient interface {
	ListPictures(ctx context.Context, in *PicturesRequest, opts ...grpc.CallOption) (*PicturesResponce, error)
}

type pictureManagemetClient struct {
	cc grpc.ClientConnInterface
}

func NewPictureManagemetClient(cc grpc.ClientConnInterface) PictureManagemetClient {
	return &pictureManagemetClient{cc}
}

func (c *pictureManagemetClient) ListPictures(ctx context.Context, in *PicturesRequest, opts ...grpc.CallOption) (*PicturesResponce, error) {
	out := new(PicturesResponce)
	err := c.cc.Invoke(ctx, "/PictureManagemet/ListPictures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PictureManagemetServer is the server API for PictureManagemet service.
type PictureManagemetServer interface {
	ListPictures(context.Context, *PicturesRequest) (*PicturesResponce, error)
}

// UnimplementedPictureManagemetServer can be embedded to have forward compatible implementations.
type UnimplementedPictureManagemetServer struct {
}

func (*UnimplementedPictureManagemetServer) ListPictures(context.Context, *PicturesRequest) (*PicturesResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPictures not implemented")
}

func RegisterPictureManagemetServer(s *grpc.Server, srv PictureManagemetServer) {
	s.RegisterService(&_PictureManagemet_serviceDesc, srv)
}

func _PictureManagemet_ListPictures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PicturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureManagemetServer).ListPictures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PictureManagemet/ListPictures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureManagemetServer).ListPictures(ctx, req.(*PicturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PictureManagemet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PictureManagemet",
	HandlerType: (*PictureManagemetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPictures",
			Handler:    _PictureManagemet_ListPictures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/picture_management_proto/picture.proto",
}
